name: Deploy S3 Bucket

on:
  push:
    branches:
    - main

jobs:
  deploy-s3:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      terraform_directory: 'terraform/s3-bucket'
      aws_region: 'us-west-2'
      bucket_name: 'raghav-terraform-s3-bucket'
      environment: 'prod'
    secrets:
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
