name: Terraform Deploy

on:
  workflow_call:
    inputs:
      terraform_directory:
        description: "Path to the Terraform directory"
        required: true
        type: string
      aws_region:
        description: "AWS Region"
        required: true
        type: string
    secrets:
      AWS_SESSION_TOKEN:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ inputs.terraform_directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: terraform plan \ -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \ -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \ -var="aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \ -var="aws_region=${{ inputs.aws_region }}"

    - name: Terraform Apply
      working-directory: ${{ inputs.terraform_directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: terraform apply -auto-approve \ -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \ -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \ -var="aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \ -var="aws_region=${{ inputs.aws_region }}"
