name: Terraform Deploy

on:
  workflow_call:
    inputs:
      terraform_directory:
        required: true
        type: string
      aws_region:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Initialize Terraform
      run: terraform -chdir=${{ inputs.terraform_directory }} init

    - name: Plan Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: terraform -chdir=${{ inputs.terraform_directory }} plan -var="aws_region=${{ inputs.aws_region }}"

    - name: Apply Terraform
      if: ${{ github.event_name == 'push' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: terraform -chdir=${{ inputs.terraform_directory }} apply -auto-approve -var="aws_region=${{ inputs.aws_region }}"
